config/routes.rb
Rails.application.routes.draw do
  
  
  resources :friend_requests
   devise_for :users,
              controllers: { registrations: 'registrations/registrations' }

  resources :users

  resources :friendships, only: [:create, :update, :destroy]

  post '/friendships/:id/confirm', to: 'friendships#confirm'

  get 'sessions/new'

  root 'static_pages#home'

  get 'help' => 'static_pages#help'

  resources :goals

 
  resources :work_sessions, only: [:create, :destroy, :update]

  

end

app/models/user.rb
class User < ActiveRecord::Base


  has_many :friendships, dependent: :destroy
  has_many :received_friendships, :class_name => "Friendship", :foreign_key => "friend_id"

  has_many :active_friends, -> { where(friendships: { accepted: true }) }, :through => :friendships, source: :friend
  has_many :received_friends, -> {where(friendships: {accepted: true} ) }, :through => :received_friendships, source: :user
  has_many :pending_friends, -> { where(friendships: { accepted: false}) }, through: :friendships, source: :friend
  has_many :requested_friends, -> { where(friendships: { accepted: false}) }, through: :received_friendships, source: :user


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :work_sessions, dependent: :destroy
  has_many :goals, dependent: :destroy

# to call all your friends

    def friends
      active_friends | received_friends
    end

# to call your pending sent or received

    def pending
        pending_friends | requested_friendships
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
	def new
		@user = User.new
	end
  def create
  	@user = User.new(user_params)
  	if @user.save
  		flash[:success] = "Welcome to TimeDojo!"
  		redirect_to @user
  	else
  		render 'new'
  	end
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 5)

    @friends = current_user.friends.paginate(page: params[:page], per_page: 5)

    #@received_friend_requests = Friendship.where({ friend_id: current_user.id, accepted: false}).paginate(page: params[:page], per_page: 5)
    @sent_friend_requests = current_user.pending_friends.paginate(page: params[:page], per_page: 5)
  end

  def show
  	@user = User.find(params[:id])
  end

  def request_friend
    if user_signed_in?
      current_user.friend_request(User.find(params[:id]))
      redirect_to users_path
    end
  end


  private
  	def user_params
  		params.require(:user).permit(:name, :email, 
  				:password, :password_confirmation)
  	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<li>
<span class="pull-left vcenter"><%= user.name %></span>

<div class="pull-right">
<% if user != current_user %>
	<% if current_user.pending_friends.include?(user) %>
		<button disabled class="btn btn-grey">Pending</button>
	<% elsif current_user.friends.include?(user)  %>
	              <%= button_to "Remove Friend", friendships_path(friend_id: user), class: "btn btn-default", method: :destroy %>
	<% else %>
	              <%= link_to "Add Friend", friendships_path(friend_id: user), class: "btn btn-primary", method: :post %>
	<% end %>
	
<% end %>            
</div>

</li>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>Your Friends</h1>

<div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Friends</h3>
        </div>
        <div class="panel-body users">
          <%= render @friends %>
          <%= will_paginate @friends %>
        </div>
      </div>

<h1> Find Friends </h1>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">All Users</h3>
  </div>
  <div class="panel-body users">
    <%= render @users %>
    <%= will_paginate @users %>
  </div>
</div>

<h1> Friend Requests </h1>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Received</h3>
  </div>
  <div class="panel-body users">
  
    <% current_user.received_friendships.where(accepted: false).each do |request| %>
    <li>
        <span class="pull-left vcenter"><%= request.user.name %></span>
      <div class="pull-right">
      <%= link_to "Accept",  friendship_path(id: request.id), method: "put", class: "btn btn-success" %>
      <%= link_to "Decline", friendship_path(id: request.id), method: :delete, class: "btn btn-danger" %>
      </div>    
    </li>
  <% end %>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Sent</h3>
  </div>
  <div class="panel-body users">
    <% current_user.friendships.where(accepted: false).each do |request| %>
    <li>
        <span class="pull-left vcenter"><%= request.friend.name %></span>
      <div class="pull-right">
        <%= button_to "Cancel", friendship_path(id: request.id), method: :delete, class: "btn btn-danger" %>
      </div>    
    </li>
  <% end %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<h1>Sign up</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages' %>

			<%= f.label :name %>
			<%= f.text_field :name, class: 'form-control' %>

			<%= f.label :email %>
			<%= f.text_field :email, class: 'form-control' %>

			<%= f.label :password %>
			<%= f.password_field :password, class: 'form-control' %>

			<%= f.label :password_confirmation %>
			<%= f.password_field :password_confirmation, class: 'form-control' %>

			<%= f.submit "Create account", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<div class="center jumbotron">
<h1> <%= @user.name %></h1>
<h4>User Profile and Statistics</h4> <br><br>

<% if @user.work_sessions.count > 0 %>

Daily productivity in sessions per day:<br><br>
<%= line_chart @user.work_sessions.group_by_day, label: "Sessions" %>

<br><br>

Average session length: <%= distance_of_time_in_words(@user.work_sessions.average(:length)) %> <br> <br>


<% else %>
User has done no sessions! 
<% end %>

</div>