config/routes.rb
Rails.application.routes.draw do
  
  
  resources :friend_requests
   devise_for :users,
              controllers: { registrations: 'registrations/registrations' }

  resources :users

  resources :friendships, only: [:create, :update, :destroy]

  post '/friendships/:id/confirm', to: 'friendships#confirm'

  get 'sessions/new'

  root 'static_pages#home'

  get 'help' => 'static_pages#help'

  resources :goals

 
  resources :work_sessions, only: [:create, :destroy, :update]

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>


  <%= javascript_include_tag "http://www.google.com/jsapi", "chartkick" %>


  <%= csrf_meta_tags %>

  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

</head>
<body>

<header class="navbar navbar-fixed-top navbar-inverse">
	<div class ="container">
		<%= link_to "TimeDojo", root_path, id: "logo" %>
		<nav>
	
			<ul class="nav navbar-nav navbar-right">
				<li> <%= link_to "Home", root_path %></li>
				<li> <%= link_to "Users", users_path %></li>
				<li> <% link_to "Help", help_path %></li>
				<% if user_signed_in? %>

					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							Account <b class="caret"></b>
						</a>
						<ul class="dropdown-menu">
							<li><%= link_to "Profile", current_user %></li>
							<li><% link_to "Settings", '#' %></li>
							<li class="divider"></li>
							<li>
								<%= link_to "Log out", destroy_user_session_path, method: "delete" %>
							</li>
						</ul>
					</li>
				<% else %>
					<li><%= link_to "Log in", new_user_session_path %></li>
				<% end %>
			</ul>
		</nav>
	</div>

</header>

<div class="bg-img"></div>
<div class="container">
	<%= flash_messages %>


	<%= yield %>

	

	 <footer class="footer">
		<small>
		TimeDojo by <a href="mailto://souleben@gmail.com"> Souleiman Benhida </a>
		</small>
	</footer>
</div>


</body>
</html>